const TokenType = {};
TokenType.CHARACTER_TOKEN = 'CHARACTER_TOKEN';
TokenType.START_TAG_TOKEN = 'START_TAG_TOKEN';
TokenType.END_TAG_TOKEN = 'END_TAG_TOKEN';
TokenType.EOF_TOKEN = 'EOF_TOKEN';
TokenType.EXP_START_IF_TOKEN = 'EXP_START_IF_TOKEN';
TokenType.EXP_THEN_IF_TOKEN = 'EXP_THEN_IF_TOKEN';
TokenType.EXP_END_IF_TOKEN = 'EXP_END_IF_TOKEN';
TokenType.EXP_START_FOR_TOKEN = 'EXP_START_FOR_TOKEN';
TokenType.EXP_END_FOR_TOKEN = 'EXP_END_FOR_TOKEN';

export default TokenType;
